### ISSUE TITLE
Is this functionality now in core? 

### ISSUE THREAD

**Issue by magnolia61** [JMAConsulting/biz.jmaconsulting.transferevent#1]
Hi Joe,
Am I correct the functionality of this extension is now in core? (CiviCRM 5.4.0)
Thanks,
Richard

**Comment by Edzelopez** [comment]
Hi @magnolia61 

I'll check on this and get back to you. It has been quite a while that we implemented this, so I'll need some time to get back to you :)

**Comment by Edzelopez** [comment]
I did a quick check on dmaster.demo.civicrm.org and used the transfer or cancel link on the participant record. If that's the functionality you are referring on core, then this is not the same thing. Core allows you to transfer participants to the same event, while this extension transfers the participant to a different event.

**Comment by magnolia61** [comment]
OK, that clarifies things. Actually we ae also looking for functionality to transfer the registration to an event of a participant to another event for the same participant (where also the contribution/payment) would move. Would this extension be able to do that?

**Comment by JoeMurray** [comment]
Although called TransferEvent this extension transfers a participant signup for Contact A in Event 1 to Contact B in Event 2. @monishdeb could you confirm that the financial aspects of the signup are also transferred over? On a quick skim I didn't see anything that would handle use cases of prices for registration being different leading to change in contribution status of Partially Paid / Refund pending. I also didn't see what would happen if the original contribution had additional line items not related to the event registration.

Let's answer questions for @magnolia61, ideally by putting an extension description into the README.md, but not do any programming to extend functionality.

**Comment by magnolia61** [comment]
> Let's answer questions for @magnolia61, ideally by putting an extension description into the README.md, but not do any programming to extend functionality.

I would indeed welcome some clarification in the readme :-)
What we are actually looking for is a way to change Event 1 to Event 2 for Contact A if he/she was registered for the wrong (similar) event. This extension seems to kind of do that.

**Comment by Edzelopez** [comment]
Hi @magnolia61 

Updated the README :)
https://github.com/JMAConsulting/biz.jmaconsulting.transferevent/blob/master/README.md
