### ISSUE TITLE
Is this extension usable fot CiviCRM 5.x.x?

### ISSUE THREAD

**Issue by magnolia61** [JMAConsulting/biz.jmaconsulting.transferevent#2]
I am using this extension since a few weeks and I am just wondering if you would think this can be safely used with CiviCRM 5.3.2 or at least the latest ESR release. I am not a developer and cannot judge if fundamental changes have been made under the hood in CiviCRM that may impact this extension.

If it's usable, the info.xml might be updated with the newer compatible version

Cheers, Richard

**Comment by JoeMurray** [comment]
I'm pretty sure it should work fine. We'll endeavour to address quickly any issues that come up using it on a recent stable version of CiviCRM.
